
@startuml

!includeurl https://raw.githubusercontent.com/marcelofpfelix/plantuml-diagrams/master/skins/skin_dark.puml

autonumber

UAC     [$alizarin]->   UAS: INVITE
UAS     [$alizarin]->   UAC: 100 Trying
UAS     [$alizarin]->   UAC: 486 Busy
UAC     [$alizarin]->   UAS: ACK

@enduml
